- name: Install httpd on ec2
  hosts: web
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes


    - name: copy index.html
      copy:
         content: "<h1>Hello from httpd by Shams!</h1>"
         dest: /var/www/html/index.html
